In [1]:
from functools import reduce
import re

import pandas as pd
import numpy as np

from src.categories import subcat_to_cat

import pickle

In [27]:
# preds_path_ls = [
#     ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
#     ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
#     ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_0sh.bin'),
#     ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_5sh.bin'),
#     ('GSOFT 0 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_0sh.bin'),
#     ('GSOFT 5 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_5sh.bin'),
# ]

preds_path_ls = [
    ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
    ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
    ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_0sh.bin'),
    ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_5sh.bin'),
    ('LoRA-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_0sh.bin'),
    ('LoRA-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_5sh.bin'),
    ('DoRA-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\DoRA-cfg18-OOD-MMLU_0sh.bin'),
    ('DoRA-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\DoRA-cfg18-OOD-MMLU_5sh.bin'),
    ('GSOFT-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_0sh.bin'),
    ('GSOFT-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_5sh.bin'),
    ('VeRA-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\VeRA-cfg1-OOD-MMLU_0sh.bin'),
    # ('VeRA-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\VeRA-cfg1-OOD-MMLU_5sh.bin'),
]

In [3]:
preds_dfs = {}

for run_name, preds_path in preds_path_ls:
    with open(preds_path, 'rb') as f:
        preds_dfs[run_name] = pickle.load(file=f)

        print(f"{run_name:16}: {preds_dfs[run_name].shape=}")

raw 0 shot      : preds_dfs[run_name].shape=(14042, 6)
raw 5 shot      : preds_dfs[run_name].shape=(14042, 6)
LoRA 0 shot     : preds_dfs[run_name].shape=(14042, 6)
LoRA 5 shot     : preds_dfs[run_name].shape=(14042, 6)
LoRA-OOD 0 shot : preds_dfs[run_name].shape=(14042, 7)
LoRA-OOD 5 shot : preds_dfs[run_name].shape=(14042, 7)
DoRA-OOD 0 shot : preds_dfs[run_name].shape=(14042, 7)
DoRA-OOD 5 shot : preds_dfs[run_name].shape=(14042, 7)
GSOFT-OOD 0 shot: preds_dfs[run_name].shape=(14042, 7)
GSOFT-OOD 5 shot: preds_dfs[run_name].shape=(14042, 7)

In [4]:
idx = 1

print(preds_dfs['GSOFT-OOD 0 shot']['text'][idx])
print(preds_dfs['GSOFT-OOD 0 shot']['model_pred'][idx])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

The following are multiple choice questions (with answers) about abstract_algebra. Output 'A', 'B', 'C', or 'D'. Full answer not needed.<|eot_id|><|start_header_id|>user<|end_header_id|>

Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the index of <p> in S_5.
A. 8
B. 2
C. 24
D. 120<|eot_id|><|start_header_id|>assistant<|end_header_id|>

C<|eot_id|>
{'generated_text': "The solution is C. 24. Here's a step by step solution."}

In [5]:
idx = 78

print(preds_dfs['DoRA-OOD 0 shot']['text'][idx])
print(preds_dfs['DoRA-OOD 0 shot']['model_pred'][idx])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

The following are multiple choice questions (with answers) about abstract_algebra. Output 'A', 'B', 'C', or 'D'. Full answer not needed.<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | For n > 1, the set {1,2, ..., n-1} is a group under multiplication modulo n. Statement 2 | There is an integer x such that 63x mod 100 = 1.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

D<|eot_id|>
{'generated_text': 'The correct answer is A. True, True.\nSolution to Statement 1:'}

In [6]:
tmp_idxs = preds_dfs['DoRA-OOD 0 shot']['model_pred'].apply(
    lambda p: (re.match('The correct answer is [ABCD]', p['generated_text']) is not None) or (re.match('The answer is [ABCD]', p['generated_text']) is not None)
)

In [7]:
def get_category(subject):
    return subcat_to_cat[subject]

# OOD_part = re.compile('The correct answer is [ABCD]')
# OOD_part_len = len('The correct answer is ')

OOD_parts = [
    (re.compile('The correct answer is [ABCD]'), len('The correct answer is ')),
    (re.compile('The answer is [ABCD]'), len('The answer is ')),
    (re.compile('The solution is [ABCD]'), len('The solution is ')),
]

def get_pred(p):
    for OOD_part, OOD_part_len in OOD_parts:
        if OOD_part.search(p):
            return p[OOD_part_len]
    
    return p[0]

def processor(row: pd.DataFrame):
    generated_text = row['model_pred']['generated_text']
    generated_text = generated_text.strip()
    

    # generated_text	subject	pred	true	corr	category
    category = get_category(row['subject'])
    pred = get_pred(generated_text)
    true = chr(ord('A') + row['answer'])
    corr = int(pred == true)

    return {
        'generated_text': generated_text,
        'subject': row['subject'],
        'pred': pred,
        'true': true,
        'corr': corr,
        'category': category
    }

In [8]:
preds_dfs['LoRA-OOD 0 shot'] = preds_dfs['LoRA-OOD 0 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['LoRA-OOD 5 shot'] = preds_dfs['LoRA-OOD 5 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['DoRA-OOD 0 shot'] = preds_dfs['DoRA-OOD 0 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['DoRA-OOD 5 shot'] = preds_dfs['DoRA-OOD 5 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['GSOFT-OOD 0 shot'] = preds_dfs['GSOFT-OOD 0 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['GSOFT-OOD 5 shot'] = preds_dfs['GSOFT-OOD 5 shot'].apply(processor, axis=1, result_type='expand')

In [9]:
preds_dfs['LoRA-OOD 0 shot'].head()

,generated_text,subject,pred,true,corr,category
0,The correct answer is D. 6. The degree of the ...,abstract_algebra,D,B,0,STEM
1,The correct answer is B. 2. The answer is B be...,abstract_algebra,B,C,0,STEM
2,"The correct answer is D. 0,4. The polynomial x^5",abstract_algebra,D,D,1,STEM
3,"The correct answer is A. True, True.\nStatemen...",abstract_algebra,A,B,0,STEM
4,The correct answer is B. 6x^2 + 4x +,abstract_algebra,B,B,1,STEM

In [10]:
preds_dfs['LoRA-OOD 5 shot'].head()

,generated_text,subject,pred,true,corr,category
0,B,abstract_algebra,B,B,1,STEM
1,C\nSolution: The order of p is 4. The order of S,abstract_algebra,C,C,1,STEM
2,D\nAnswer format: A/B/C/D. Full answer not nee...,abstract_algebra,D,D,1,STEM
3,D,abstract_algebra,D,B,0,STEM
4,B\nSolution: f(x) = 4x - 5 =,abstract_algebra,B,B,1,STEM

In [11]:
preds_dfs['GSOFT-OOD 5 shot'].head()

  generated_text           subject pred true  corr category
0              B  abstract_algebra    B    B     1     STEM
1              D  abstract_algebra    D    C     0     STEM
2              D  abstract_algebra    D    D     1     STEM
3              D  abstract_algebra    D    B     0     STEM
4           B. 6  abstract_algebra    B    B     1     STEM

In [13]:
preds_dfs['DoRA-OOD 5 shot']['pred'].value_counts()

pred
B    4436
A    3809
C    3729
D    2068
Name: count, dtype: int64

In [14]:
acc_by_subjects = pd.DataFrame({
    'subject': list(set.union(
        *map(
            lambda df: set(df['subject']),
            preds_dfs.values()
        )
    ))
})

print(f"Subjects: {acc_by_subjects['subject']}")

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['subject', 'corr']].groupby(['subject'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_subjects = acc_by_subjects.merge(
        acc_df,
        left_on='subject',
        right_on='subject',
        how='right'
    )

Subjects: 0                        abstract_algebra
1                  high_school_statistics
2                 professional_psychology
3                         college_biology
4                            formal_logic
5                              management
6            high_school_computer_science
7                         world_religions
8                         moral_scenarios
9                       logical_fallacies
10                    high_school_biology
11                          miscellaneous
12                      college_chemistry
13                                anatomy
14                           econometrics
15                  high_school_chemistry
16                high_school_mathematics
17                        human_sexuality
18                      us_foreign_policy
19                       professional_law
20                     conceptual_physics
21                  professional_medicine
22                professional_accounting
23              high_school_world_history
24                          jurisprudence
25                 electrical_engineering
26             high_school_macroeconomics
27                 elementary_mathematics
28                      computer_security
29                             philosophy
30                        college_physics
31                              nutrition
32                  high_school_geography
33                               virology
34                            human_aging
35               college_computer_science
36                    college_mathematics
37             high_school_microeconomics
38                              astronomy
39                 high_school_psychology
40                       machine_learning
41                              marketing
42                     clinical_knowledge
43                    high_school_physics
44                       public_relations
45                         moral_disputes
46                       medical_genetics
47                       college_medicine
48    high_school_government_and_politics
49                             prehistory
50                      international_law
51                        business_ethics
52                 high_school_us_history
53                           global_facts
54                       security_studies
55           high_school_european_history
56                              sociology
Name: subject, dtype: object

In [15]:
acc_by_subjects

,subject,raw 0 shot,raw 5 shot,LoRA 0 shot,LoRA 5 shot,LoRA-OOD 0 shot,LoRA-OOD 5 shot,DoRA-OOD 0 shot,DoRA-OOD 5 shot,GSOFT-OOD 0 shot,GSOFT-OOD 5 shot
0,abstract_algebra,0.350000,0.310000,0.310000,0.340000,0.290000,0.300000,0.350000,0.420000,0.340000,0.300000
1,anatomy,0.674074,0.666667,0.629630,0.614815,0.607407,0.637037,0.637037,0.629630,0.666667,0.681481
2,astronomy,0.750000,0.723684,0.717105,0.730263,0.723684,0.677632,0.723684,0.671053,0.769737,0.756579
3,business_ethics,0.660000,0.670000,0.610000,0.650000,0.730000,0.640000,0.660000,0.650000,0.690000,0.740000
4,clinical_knowledge,0.716981,0.747170,0.743396,0.769811,0.698113,0.698113,0.694340,0.705660,0.732075,0.724528
5,college_biology,0.715278,0.756944,0.784722,0.791667,0.715278,0.729167,0.729167,0.729167,0.736111,0.784722
6,college_chemistry,0.450000,0.460000,0.480000,0.490000,0.410000,0.400000,0.400000,0.380000,0.420000,0.440000
7,college_computer_science,0.470000,0.570000,0.470000,0.540000,0.490000,0.470000,0.460000,0.460000,0.480000,0.490000
8,college_mathematics,0.350000,0.350000,0.280000,0.380000,0.270000,0.270000,0.360000,0.290000,0.330000,0.350000
9,college_medicine,0.618497,0.641618,0.664740,0.647399,0.560694,0.572254,0.595376,0.601156,0.641618,0.606936
10,college_physics,0.441176,0.401961,0.460784,0.529412,0.431373,0.411765,0.431373,0.372549,0.460784,0.411765
11,computer_security,0.770000,0.760000,0.730000,0.790000,0.770000,0.760000,0.760000,0.700000,0.790000,0.800000
12,conceptual_physics,0.548936,0.591489,0.570213,0.557447,0.557447,0.565957,0.536170,0.548936,0.582979,0.578723
13,econometrics,0.500000,0.570175,0.552632,0.561404,0.456140,0.543860,0.473684,0.561404,0.508772,0.587719
14,electrical_engineering,0.579310,0.606897,0.600000,0.606897,0.531034,0.537931,0.537931,0.524138,0.600000,0.606897
15,elementary_mathematics,0.460317,0.441799,0.489418,0.455026,0.428571,0.420635,0.420635,0.396825,0.449735,0.439153
16,formal_logic,0.388889,0.500000,0.468254,0.500000,0.428571,0.396825,0.396825,0.380952,0.500000,0.460317
17,global_facts,0.420000,0.420000,0.400000,0.420000,0.440000,0.460000,0.400000,0.400000,0.430000,0.470000
18,high_school_biology,0.790323,0.796774,0.774194,0.774194,0.770968,0.729032,0.709677,0.677419,0.738710,0.745161
19,high_school_chemistry,0.453202,0.507389,0.512315,0.546798,0.507389,0.492611,0.502463,0.482759,0.566502,0.551724
20,high_school_computer_science,0.650000,0.700000,0.740000,0.760000,0.670000,0.700000,0.650000,0.600000,0.690000,0.680000
21,high_school_european_history,0.715152,0.769697,0.757576,0.757576,0.763636,0.721212,0.727273,0.666667,0.781818,0.757576
22,high_school_geography,0.777778,0.813131,0.803030,0.818182,0.787879,0.772727,0.803030,0.797980,0.838384,0.808081
23,high_school_government_and_politics,0.849741,0.911917,0.901554,0.901554,0.829016,0.829016,0.839378,0.834197,0.865285,0.865285
24,high_school_macroeconomics,0.610256,0.671795,0.610256,0.648718,0.620513,0.615385,0.587179,0.579487,0.612821,0.633333
25,high_school_mathematics,0.329630,0.351852,0.270370,0.370370,0.329630,0.337037,0.244444,0.307407,0.307407,0.325926
26,high_school_microeconomics,0.731092,0.760504,0.710084,0.747899,0.705882,0.689076,0.684874,0.668067,0.764706,0.747899
27,high_school_physics,0.357616,0.430464,0.403974,0.437086,0.384106,0.430464,0.357616,0.430464,0.403974,0.483444
28,high_school_psychology,0.823853,0.831193,0.853211,0.858716,0.805505,0.787156,0.822018,0.792661,0.833028,0.827523
29,high_school_statistics,0.481481,0.518519,0.541667,0.555556,0.495370,0.486111,0.435185,0.421296,0.453704,0.458333
30,high_school_us_history,0.759804,0.764706,0.813725,0.803922,0.789216,0.769608,0.759804,0.725490,0.799020,0.774510
31,high_school_world_history,0.776371,0.835443,0.827004,0.848101,0.772152,0.755274,0.780591,0.755274,0.831224,0.827004
32,human_aging,0.690583,0.735426,0.681614,0.730942,0.672646,0.708520,0.730942,0.713004,0.677130,0.713004
33,human_sexuality,0.740458,0.778626,0.725191,0.778626,0.679389,0.740458,0.709924,0.687023,0.732824,0.717557
34,international_law,0.735537,0.785124,0.776860,0.752066,0.719008,0.727273,0.677686,0.743802,0.727273,0.785124
35,jurisprudence,0.703704,0.768519,0.768519,0.768519,0.731481,0.768519,0.750000,0.703704,0.759259,0.740741
36,logical_fallacies,0.730061,0.748466,0.699387,0.705521,0.687117,0.656442,0.699387,0.662577,0.730061,0.766871
37,machine_learning,0.428571,0.526786,0.544643,0.526786,0.491071,0.535714,0.508929,0.517857,0.500000,0.526786
38,management,0.786408,0.805825,0.834951,0.844660,0.796117,0.776699,0.854369,0.796117,0.854369,0.844660
39,marketing,0.871795,0.910256,0.901709,0.910256,0.884615,0.867521,0.901709,0.888889,0.893162,0.880342
40,medical_genetics,0.740000,0.780000,0.780000,0.730000,0.760000,0.700000,0.740000,0.730000,0.770000,0.740000
41,miscellaneous,0.809706,0.819923,0.812261,0.821201,0.800766,0.798212,0.802043,0.787995,0.828863,0.813538
42,moral_disputes,0.656069,0.760116,0.667630,0.736994,0.661850,0.632948,0.644509,0.644509,0.667630,0.696532
43,moral_scenarios,0.271508,0.469274,0.239106,0.370950,0.293855,0.417877,0.279330,0.318436,0.310615,0.440223
44,nutrition,0.732026,0.764706,0.735294,0.741830,0.712418,0.666667,0.686275,0.660131,0.738562,0.748366
45,philosophy,0.681672,0.733119,0.720257,0.723473,0.681672,0.672026,0.678457,0.662379,0.697749,0.710611
46,prehistory,0.719136,0.734568,0.709877,0.756173,0.719136,0.700617,0.700617,0.700617,0.734568,0.740741
47,professional_accounting,0.510638,0.542553,0.482270,0.485816,0.503546,0.489362,0.507092,0.464539,0.485816,0.514184
48,professional_law,0.415906,0.462190,0.482399,0.485658,0.415906,0.398957,0.419817,0.388527,0.460887,0.451108
49,professional_medicine,0.746324,0.694853,0.731618,0.746324,0.654412,0.658088,0.639706,0.625000,0.698529,0.661765
50,professional_psychology,0.633987,0.694444,0.696078,0.718954,0.668301,0.656863,0.658497,0.665033,0.689542,0.699346
51,public_relations,0.645455,0.672727,0.700000,0.681818,0.709091,0.672727,0.709091,0.672727,0.672727,0.654545
52,security_studies,0.702041,0.734694,0.722449,0.726531,0.710204,0.706122,0.702041,0.665306,0.714286,0.722449
53,sociology,0.850746,0.850746,0.845771,0.855721,0.835821,0.791045,0.766169,0.786070,0.845771,0.820896
54,us_foreign_policy,0.860000,0.840000,0.850000,0.910000,0.860000,0.850000,0.810000,0.840000,0.850000,0.850000
55,virology,0.463855,0.506024,0.469880,0.493976,0.469880,0.506024,0.481928,0.487952,0.500000,0.524096
56,world_religions,0.801170,0.812865,0.824561,0.818713,0.783626,0.777778,0.783626,0.789474,0.801170,0.795322

In [16]:
acc_by_categories = pd.DataFrame({
    'category': list(set.union(
        *map(
            lambda df: set(df['category']),
            preds_dfs.values()
        )
    ))
})

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['category', 'corr']].groupby(['category'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_categories = acc_by_categories.merge(
        acc_df,
        left_on='category',
        right_on='category',
        how='right'
    )

In [17]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('5 shot' not in s),
    acc_by_categories.columns
))]

,category,raw 0 shot,LoRA 0 shot,LoRA-OOD 0 shot,DoRA-OOD 0 shot,GSOFT-OOD 0 shot
0,STEM,0.525182,0.540755,0.519549,0.501325,0.533797
1,humanities,0.527099,0.556217,0.533688,0.526249,0.563018
2,"other (business, health, misc.)",0.706663,0.709130,0.690623,0.694016,0.714682
3,social sciences,0.721807,0.746831,0.721807,0.713682,0.743581

In [18]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('0 shot' not in s),
    acc_by_categories.columns
))]

,category,raw 5 shot,LoRA 5 shot,LoRA-OOD 5 shot,DoRA-OOD 5 shot,GSOFT-OOD 5 shot
0,STEM,0.546720,0.561962,0.515905,0.493704,0.539430
1,humanities,0.603826,0.591711,0.543464,0.516684,0.586823
2,"other (business, health, misc.)",0.724244,0.719926,0.685071,0.679827,0.713757
3,social sciences,0.758531,0.766006,0.714332,0.707182,0.744556

In [19]:
total_res = pd.DataFrame(columns=['run_name', 'accuracy', 'correctness'])

for run_name, preds_df in preds_dfs.items():
    total_accuracy = preds_df['corr'].mean()
    total_correctness = (preds_df['pred'] != 'I').mean()

    total_res = pd.concat([
        total_res,
        pd.DataFrame({
            'run_name': [run_name],
            'accuracy': [total_accuracy],
            'correctness': [total_correctness],
        })
    ])

C:\Users\Vladimir\AppData\Local\Temp\ipykernel_15148\2066953499.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  total_res = pd.concat([

In [20]:
total_res

           run_name  accuracy  correctness
0        raw 0 shot  0.610810     0.997151
0        raw 5 shot  0.653255     0.999217
0       LoRA 0 shot  0.629967     0.992024
0       LoRA 5 shot  0.653112     1.000000
0   LoRA-OOD 0 shot  0.608104     1.000000
0   LoRA-OOD 5 shot  0.607677     1.000000
0   DoRA-OOD 0 shot  0.600698     1.000000
0   DoRA-OOD 5 shot  0.591155     1.000000
0  GSOFT-OOD 0 shot  0.631320     0.999929
0  GSOFT-OOD 5 shot  0.640507     1.000000

In [26]:
(0.653255 - 0.640507) * 100

1.2747999999999982